version: "3.8"
services:
  too-doo:
    build: .
    ports:
      - "5000:3000"
    container_name: too-doo
    env_file:
      - .env
    restart: on-failure
    # networks:
    #   - backbone
#   nginx:
#     restart: always
#     build:
#       context: ./nginx
#     ports:
#       - "80:80"
#     networks:
#       - backbone

# networks:
#   backbone:
#     driver: bridge
